name: "Home Assistant Guest"
description: "A secondary, isolated instance of Home Assistant for guest users with HACS pre-installed."
version: "0.0.1"
slug: "ha_guest"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  8123/tcp: 8223
map:
  - type: addon_config
    path: /config
    read_only: false
